### ISSUE TITLE
backend: attach and trace endpoints

### ISSUE THREAD

**Issue by tcourdy** [team-worm/spice#12]
given a path that has a binary executable.  Attach to a process via the debug library and capture output from the binary and send to front end as serialized JSON

**Comment by rpjohnst** [comment]
There are two types of output you might want to capture:
* `stdout`/`stderr`, which the debug library does not currently handle, but which you could port from the Rust stdlib (which has its own `Command`/`Child` objects that ours are inspired by)
* `OutputDebugString`, which the debug library does support but which only exists (afaik) on Windows and only when the child process calls that function and not, say, `printf`.
